'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _Buttons = require('../components/Buttons/');

var _Buttons2 = _interopRequireDefault(_Buttons);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = [{ type: 'inline', label: 'bold', style: 'BOLD', icon: _Buttons2.default.BoldIcon }, { type: 'inline', label: 'italic', style: 'ITALIC', icon: _Buttons2.default.ItalicIcon }, { type: 'inline', label: 'strikethrough', style: 'STRIKETHROUGH', icon: _Buttons2.default.Strike }, { type: 'inline', label: 'code', style: 'CODE', icon: _Buttons2.default.Code }, { type: 'inline', label: 'dropcap', style: 'DROPCAP', icon: _Buttons2.default.Dropcap }, { type: 'entity', label: 'link', style: 'link', entity: 'LINK', icon: _Buttons2.default.LinkIcon }, { type: 'separator', label: 'separator' }, { type: 'block', label: 'ul', style: 'unordered-list-item', icon: _Buttons2.default.ULIcon }, { type: 'block', label: 'ol', style: 'ordered-list-item', icon: _Buttons2.default.OLIcon }, { type: 'block', label: 'h2', style: 'header-two', icon: _Buttons2.default.H2Icon }, { type: 'block', label: 'blockquote', style: 'blockquote', icon: _Buttons2.default.BlockQuoteIcon }]; /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * Copyright (c) 2016, Globo.com (https://github.com/globocom)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * Copyright (c) 2016, vace.nz (https://github.com/vacenz)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * License: MIT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */